# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sewa-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sewa-iOS
pod 'Alamofire', '~> 5.0.0-rc.3'
  pod 'LTHRadioButton'
    pod 'SwiftyJSON', '~> 4.0'


  target 'Sewa-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Sewa-iOSUITests' do
    # Pods for testing
  end

end
